version: "3.7"

services:
  webserver:
    build: .
    volumes:
      - ./webroot:/var/www/html
      - ./php:/usr/local/etc/php 
    ports: 
      - 8789:80
    links:
      - 'pgsqldb:pgsql'
    depends_on:
      - pgsqldb
  pgsqldb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    restart: always
  